# _config.yml
# configuration du site (utilis√© dans les templates)
title: "Serveur mental"
description: "Mon journal / notes / progression"
theme: jekyll-theme-midnight

# Navigation (menu)
nav:
  - name: "Accueil"
    link: /
  - name: "Triathlon"
    link: /triathlon/
  - name: "Notes"
    link: /notes/
  - name: "Progression"
    link: /progression/
